baseURL: 'https://kluophysics.github.io/'
languageCode: en-us
title: Luo's Theory Lab
theme: hugo-sewing
DefaultContentLanguage: en
footnotereturnlinkcontents: ↩
pygmentsuseclasses: true
staticDir:
  - static
disableKinds:
  - GitInfo
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: People
      url: /people/
      weight: 2
    - name: Research
      url: /research/
      weight: 3
    - name: Teaching
      url: /teaching/
      weight: 4
    - name: Publications
      url: /publications/
      weight: 5
    - name: Talks
      url: /talks/
      weight: 6
    - name: Blog
      url: /blog/
      weight: 7
    - name: Gallery
      url: /gallery/
      weight: 8
    # - name: Contact
    #   url: /contact/
    #   weight: 9
markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      linkify: false
frontmatter:
  lastmod:
    - lastmod
    - ':git'
    - date
    - publishDate
params:
  authorName: Kai Luo
  enableTheme: true
  enableVisitor: false
  enableUpdated: false
  enableMemo: false
  enableGiscus: true
  enableimgloop: true
  toc: true
  Theme:
    url: 'https://github.com/HaiyanKong/hugo-sewing'
    name: Hugo-Sewing
  visitor:
    src: ''
  memo:
    memos: ''
    limit: ' '
    creatorId: ' '
    domId: ' '
    twiEnv: ''
  giscus:
    data_repo: ''
    data_repo_id: ''
    data_category: Announcements
    data_category_id: ''
    data_mapping: pathname
    data_strict: '0'
    data_reactions_enabled: '1'
    data_emit_metadata: '0'
    data_input_position: top
    data_theme: noborder_light
    data_lang: en
    crossorigin: anonymous
permalinks:
  blog: '/blog/:year/:month/:slug/'
